services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  service1:
    build: ./service1
    ports:
      - "5001:5001"

  service-camilo:
    build: ./serviceCam
    ports:
      - "5007:5007"
